name=MecLabLibrary
version=1.0.0
author=Grayson Camara
sentence=Easy functions for controlling Festo MecLab stuff
paragraph=A library for controlling Festo MecLab components with the P1AM-100 microcontroller. Provides easy-to-use functions for many components, as well as classes for whole assemblies.
category=Signal Input/Output
architectures=avr, samd